### ISSUE TITLE
Would you like to move into the fisherman organization?

### ISSUE THREAD

**Issue by bucaran** [derhuerst/vibrant#3]
Hi @derhuerst.

fisherman just turn 2.0 and some things changed, namely, we don't depend on an index anymore. In order to improve discoverability I am trying to reach out to some of plugin authors and ask them if they would like to join the fisherman org and bring their plugins / themes with them.

How does that sound?

**Comment by derhuerst** [comment]
My prompt is not written nicely and doesn't make use of the (nicely separated btw) modules of fishery. So I think it's not sufficient as a "poster project".

If you still intend to move it, tell what I need to do, except moving it into the org.

**Comment by bucaran** [comment]
@derhuerst No problem. I get it :)

**Comment by bucaran** [comment]
@derhuerst Please update the install instructions to:

```
fisher derhuerst/vibrant
```

Since we are not using the index anymore, we need the full namespace to install modules that are not in the fisherman org.

**Comment by derhuerst** [comment]
So shall I move the repo?

**Comment by bucaran** [comment]
That'd be great, let me add you to the org too.

**Comment by bucaran** [comment]
@derhuerst I made you an admin!

So, I noticed this repo has **two** licenses. Why?

It would be great for consistency if we could make the README more alike: https://github.com/fisherman/prompt

**Comment by derhuerst** [comment]
> So, I noticed this repo has two licenses. Why?

Do you mean the broken license link in the readme? Will remove that.

> It would be great for consistency if we could make the README more alike: https://github.com/fisherman/prompt

Will make it similar.

**Comment by bucaran** [comment]
Thanks.

**Comment by bucaran** [comment]
Why did you change the license from MIT to the current one? Does it have any advantages over MIT?

I really never use anything but MIT, but I could learn.

**Comment by derhuerst** [comment]
@bucaran It is functionally equivalent. Some unnecessary stuff has been removed. Also, see [*United States vs. Swartz*](https://en.wikipedia.org/wiki/United_States_v._Swartz#Reactions.2C_complaints_and_post-dismissal_motions).
